version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      mcsnet:
        ipv4_address: 172.20.0.6
  aggregator:

    depends_on:
      - rabbitmq
    build: ./aggregator

    deploy:
      mode: replicated
      replicas: 2

    networks:
      - mcsnet

  api-gateway:

    depends_on:
      - rabbitmq

    deploy:
      mode: replicated
      replicas: 2
    build: ./api gateway
    expose:
      - "8080"

    networks:
      - mcsnet
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    ports:
      - "4000:4000"

    networks:
      - mcsnet
  call:
    build: ./call
    depends_on:
      - rabbitmq

    deploy:
      mode: replicated
      replicas: 2

    networks:
      - mcsnet

  phone:
    depends_on:
      - rabbitmq
    build: ./phone
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - mcsnet
networks:
  mcsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24